# Configuration for the Labeler GitHub action, executed by
# .github/workflows/labeler.yml.
#
# The basic syntax is [label]: [path patterns].
#
# For more details on the configuration please see:
# https://github.com/marketplace/actions/labeler

# TODO(cookiecutter): Add different parts of the source
# For example:
#
# "part:module":
#   - "src/frequenz/lib/client_common/module/**"
#
# "part:other":
#   - "src/frequenz/lib/client_common/other/**"
#
# # For excluding some files (in this example, label "part:complicated"
# # everything inside src/ with a .py suffix, except for src/__init__.py)
# "part:complicated":
#   - any:
#       - "src/**/*.py"
#   - all:
#       - "!src/__init__.py"
#
# Please have in mind that that the part:xxx labels need to
# be created in the GitHub repository.

"part:docs":
  - changed-files:
    - any-glob-to-any-file:
      - "**/*.md"
      - "docs/**"
      - "examples/**"
      - LICENSE

"part:grid":
  - "src/frequenz/client/common/grid*"
  - "src/frequenz/client/common/grid/**"

"part:location":
  - "src/frequenz/client/common/location*"
  - "src/frequenz/client/common/location/**"

"part:market":
  - "src/frequenz/client/common/market*"
  - "src/frequenz/client/common/market/**"

"part:metrics":
  - "src/frequenz/client/common/metrics*"
  - "src/frequenz/client/common/metrics/**"

"part:microgrid":
  - "src/frequenz/client/common/microgrid*"
  - "src/frequenz/client/common/microgrid/**"

"part:pagination":
  - "src/frequenz/client/common/pagination*"
  - "src/frequenz/client/common/pagination/**"

"part:tests":
  - changed-files:
    - any-glob-to-any-file:
      - "**/conftest.py"
      - "tests/**"

"part:tooling":
  - changed-files:
    - any-glob-to-any-file:
      - "**/*.ini"
      - "**/*.toml"
      - "**/*.yaml"
      - "**/*.yml"
      - "**/conftest.py"
      - ".editorconfig"
      - ".git*"
      - ".git*/**"
      - "docs/*.py"
      - CODEOWNERS
      - MANIFEST.in
      - noxfile.py
